apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasource-syncer
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasource-syncer
  template:
    metadata:
      labels:
        app: datasource-syncer
    spec:
      containers:
        - name: datasource-syncer
          image: gke.gcr.io/prometheus-engine/datasource-syncer:v0.18.1-gke.2
